# Generated by Django 5.0 on 2024-01-02 10:19

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('avatar_url', models.CharField(max_length=200)),
                ('interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followed_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), size=None)),
                ('following', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), size=None)),
                ('bookmarked_posts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('profile_url', models.CharField(max_length=200)),
                ('premium_member', models.BooleanField(default=False)),
                ('premium_type', models.IntegerField()),
            ],
        ),
    ]
