# Generated by Django 5.0 on 2024-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_comment_users_notiifications_posts_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(related_name='followings', to='main.users'),
        ),
    ]
