# Generated by Django 5.0 on 2024-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='child_topic_id',
            field=models.ManyToManyField(blank=True, related_name='child_topics', to='main.topic'),
        ),
    ]
