# Generated by Django 5.0 on 2024-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_topic_child_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_users', to='main.question'),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followings', to='main.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='interest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
