# Generated by Django 5.0 on 2024-01-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_answer_answer_id_alter_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
